### ISSUE TITLE
template/projects miss .env file

### ISSUE THREAD

**Issue by TokenxyWZY** [clemlak/create-truffle-dapp#3]
{ Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/.env'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/.env' }
/usr/local/lib/node_modules/create-truffle-dapp/createTruffleDapp.js:162
        buf = buf.replace(/_mnemonic_placeholder_/g, answers.mnemonic);
                  ^

TypeError: Cannot read property 'replace' of undefined
    at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/create-truffle-dapp/createTruffleDapp.js:162:19)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by clemlak** [comment]
Hey! Can you explain me the context of this issue? What were you trying to do? Create a new project?

**Comment by antwal** [comment]
same problem

```
Welcome to create-truffle-dapp!

? Do you want to set an Infura project ID? No
? Do you want to set a mnemonic? No
? Do you want to create a default configuration file for a Solidity linter? Solium

Creating test4 in /Users/antwal/Projects/dApp-test...

[Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/.env'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/.env'
}
[Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/.gitignore'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/.gitignore'
}
[Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/truffle.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/truffle.js'
}
[Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/create-truffle-dapp/templates/project/package.json'
}
/usr/local/lib/node_modules/create-truffle-dapp/createTruffleDapp.js:208
      const buf = data.replace(/_project_placeholder_/g, projectName);
                       ^

TypeError: Cannot read property 'replace' of undefined
    at ReadFileContext.callback (/usr/local/lib/node_modules/create-truffle-dapp/createTruffleDapp.js:208:24)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13)

```
